blog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from .views import ContactView, SearchResultsView
# from .views import SearchResultsView


app_name = 'blog'
urlpatterns = [
   #url(r'^$', views.post_list, name='post_list'),  # for redirect from http://127.0.0.1:8000/blog
   url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
   url(r'^post/new/$', views.post_new, name='post_new'),
   url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
   path('index', views.index, name='home'),
   # path('login', TemplateView.as_view(template_name="blog/login_prev.html")),
   path('about', TemplateView.as_view(template_name="blog/about.html"), name='about'),
   path('contact', ContactView.as_view(), name='contact'),
   # path('contact', views.get_name, name='contact'),
   path('thanks/', TemplateView.as_view(template_name="blog/thanks.html"), name='thanks'),
   path('search/', SearchResultsView.as_view(), name='search_results'),
   path('', views.post_list, name='post_list'),  # for redirect from http://127.0.0.1:8000/blog

    # note: убирать .html из адресной строки /htaccess????
]

mysite/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from blog import views
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('registration/', include('registration.urls')),
    path('account/', include('account.urls')),
    path('', views.index),# to do: add common app for index, about, contacts
    path('404page', TemplateView.as_view(template_name="404.html"), name='404page'),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Teacher(models.Model):
    name = models.CharField(max_length=80)
    age = models.IntegerField()

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class ContactForm(forms.Form):
    my_default_errors = {
        'required': 'This field is required',
        'invalid': 'Enter a valid value'
    }  # в шаблоне contact.html отменить встроенную проверку данных, добавив аттрибут novalidate

    error_css_class = "has-error"

    name = forms.CharField(help_text="Введите свое имя",
                           widget=forms.TextInput(attrs={'placeholder': 'Enter Your Name',
                                                         "class": "form-control name"}),
                           error_messages=my_default_errors)

    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Enter Your E-Mail',
                                                            "class": "form-control email"}),
                             error_messages=my_default_errors)
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter Your Message',
                                                           "class": "form-control"}),
                              error_messages=my_default_errors)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass






blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import View

from .models import Post
from .forms import PostForm
from django.http import HttpResponse, HttpResponseRedirect
from blog.forms import ContactForm
from django.views.generic.edit import FormView
from django.views.generic import ListView
from django.db.models import Q


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    title = 'New post'
    return render(request, 'blog/post_edit.html', {'form': form, 'title': title})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    title = 'Edit post #' + pk
    return render(request, 'blog/post_edit.html', {'form': form, 'title': title})


def index(request):
    return render(request, "blog/index.html")


class ContactView(FormView):
    template_name = 'blog/contact.html'
    form_class = ContactForm
    success_url = 'thanks'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super().form_valid(form)


# def get_name(request):
#     # if this is a POST request we need to process the form data
#     if request.method == 'POST':
#         # create a form instance and populate it with data from the request:
#         form = ContactForm(request.POST)
#         # check whether it's valid:
#         if form.is_valid():
#             # process the data in form.cleaned_data as required
#             name = form.cleaned_data["name"]
#             # redirect to a new URL:
#             return redirect('blog:thanks')
#
#     # if a GET (or any other method) we'll create a blank form
#     else:
#         form = ContactForm()
#
#     return render(request, 'blog/contact.html', {'form': form})


class SearchResultsView(ListView):
    model = Post
    template_name = 'blog/search_results.html'

    # queryset = Post.objects.filter(name__icontains='Boston')

    def get_queryset(self):  # новый
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(
            Q(title__icontains=query) | Q(text__icontains=query)
        )
        return object_list



blog/templates/blog/about.html
{% extends 'base.html' %}
{% block title %}About Us{% endblock title %}
{% block content %}
{% load static %}
<!-- ============ Our history ========== -->
		<section class="history_sec">
			<div class="container">
				<div class="row">
					<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 left-side">
						<h2>Our Histroy</h2>
						<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium dolore mque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi archi- tecto beatae vitae dict eaque ipsa quae ab illo inventore veritatis et quasi Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium dolore mque laudantium, totam rem aperiam, eaque ipsa quae abarchitecto.</p>
						<ul>
							<li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;Financial Managment and Consulting</a></li>
							<li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;Advice and Assistance Investing</a></li>
							<li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;Comprehensive Support for Your Business</a></li>
						</ul>
					</div>
					<div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 right_side">
						<img class="img-responsive" src="{% static 'images/about/1.jpg' %}" alt="image">
						<h3>Company Mission </h3>
						<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium dolore mque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto </p>
					</div>
				</div>
			</div>
		</section>
<!-- ============ /Our history ========== -->

<!-- ==========Value Of our Company ======= -->
		<section class="company_value_sec">
			<div class="company_value_opacity">
				<div class="container">
					<div class="company_value_heading">
						<div class="title-box">
							<h2>Value of our <br>Company</h2>
						</div>
						<div class="text-box">
							<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occae- cat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
						</div>
					</div> <!-- End Row -->
					<div class="row value_fact">
						<span class="timer" data-from="1" data-to="12" data-speed="5000" data-refresh-interval="50">12</span><p>Years of <br>Experiences</p>
						<span class="timer" data-from="10" data-to="54" data-speed="5000" data-refresh-interval="50">54</span><p>Professional <br>Advisors</p>
						<span class="timer"  data-from="10" data-to="40" data-speed="5000" data-refresh-interval="50">40</span><p>news cases <br>every years</p>
						<span class="timer" data-from="10" data-to="89" data-speed="5000" data-refresh-interval="50">89</span><p class="case">Registered <br>Cases</p>
					</div>
				</div>
			</div>
		</section>
<!-- ==========/Value Of our Company ======= -->

<!-- ======= Testimonial & Company Values ======= -->
		<section class="testimonial_sec clear_fix">
			<div class="container">
				<div class="row">
					<div  class="col-lg-5 col-md-12 col-sm-12 col-xs-12 testimonial_container">
						<div class="sec-title">
							<h2>Testimonials</h2>
						</div>
						<div id="owl">
							<div>
								<div class="testimonial">
									<img class="round_img" src="{% static 'images/7.jpg' %}" alt="images">
									<div class="float_right client_info">
										<p>MeFinance is Great Firm</p>
										<span>Michale John (CEO & Founder)</span>
										<ul>
											<li><a href=""></a></li>
											<li><a href=""></a></li>
											<li><a href=""></a></li>
											<li><a href=""></a></li>
											<li><a href=""></a></li>
										</ul>
									</div>
								</div>
								<p class="john_speach">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia numquam eius modi. Neque porro quisquam est, qui dolorem ipsum </p>
								<img src="{% static 'images/sign.jpg' %}" alt="images">
							</div>
						</div> <!-- End owl -->
					</div>
					<div class="col-lg-7 col-md-12 col-sm-12 col-xs-12 company">
						<h2>Our Company Values</h2>
						<div class="company-tab">
							<ul class="nav nav-pills nav-justified">
							    <li class="active"><a data-toggle="pill" href="#menu1">Quality</a></li>
							    <li><a data-toggle="pill" href="#menu2">Commitment</a></li>
							    <li><a data-toggle="pill" href="#menu3">Success</a></li>
						  	</ul>

							 <div class="tab-content">
							    <div id="menu1" class="tab-pane fade in active">
							      <h3>Our Company Quality</h3>
							      <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit. Red quia numquam eius modi. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur</p>
							      <ul class="p0">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							      <ul class="list-two">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							    </div>
							    <div id="menu2" class="tab-pane fade">
							      <h3>Our Company Quality</h3>
							      <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit. Red quia numquam eius modi. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur</p>
							      <ul class="p0">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							      <ul class="list-two">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							    </div>
							    <div id="menu3" class="tab-pane fade">
							      <h3>Our Company Quality</h3>
							      <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit. Red quia numquam eius modi. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur</p>
							      <ul class="p0">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							      <ul class="list-two">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							    </div>
							 </div>
						</div>
					</div>
				</div> <!-- End row -->
			</div> <!-- End Container -->
		</section> <!-- testimonial -->
<!-- ======= /Testimonial & Company Values ======= -->


{% endblock content %}

blog/templates/blog/contact.html
{% extends 'base.html' %}
{% block title %}Contact Us{% endblock title %}
{% block content %}
{% load static %}
<!-- =================== Contact us container ============== -->
		<section class="contact_us_container">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="text-align:center;"> <!-- section title -->
						<h2>Get In Touch With Us</h2>
						<p>You can talk to our online representative at any time. Please use our Live Chat System on our website or <br>
						Fill up below instant messaging programs.</p>
					</div> <!-- End section title -->
					<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 form_holder"> <!-- form holder -->
						<form method="POST" novalidate>
							{% csrf_token %}
							<div>
								{% for field in form %}
								<div class="form-group">
            						{{field.label_tag}}
            						<div>{{field}}</div>
            						<div class="error">{{field.errors}}</div>
        						</div>
        						{% endfor %}
        					</div>
						    <button type="submit" class="submit">submit now <i class="fa fa-arrow-circle-right"></i></button>
						</form> <!-- End form holder -->

					</div>
					<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pull-right address">
						<address>
							<div class="icon_holder float_left"><span class="icon icon-Pointer"></span></div>
							<div class="address_holder float_left">13005 Greenville Avenue <br> California, TX 70240 <br>New York</div>
						</address>
						<address class="clear_fix">
							<div class="icon_holder float_left"><span class="icon icon-Plaine"></span></div>
							<div class="address_holder float_left">contact@mefinance.com <br>support@mefinance.com</div>
						</address>
						<address class="clear_fix">
							<div class="icon_holder float_left"><span class="icon icon-Phone2"></span></div>
							<div class="address_holder float_left">+ (1800) 456 7890 <br> + (1544) 456 7890</div>
						</address>
					</div>
				</div>
			</div>
		</section>

<!-- =================== /Contact us container ============== -->
{% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}Index{% endblock title %}
{% block content %}
{% load static %}
<!-- ======= Welcome section ======= -->
		<section class="welcome_sec">
			<div class="container">
				<div class="row welcome_heading">
					<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
						<h2>We offer <br>Different Services</h2>
					</div>
					<div class="col-lg-8 col-md-8 col-sm-7 col-xs-12">
						<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Consect petur adipiscing elit.</p>
					</div>
				</div> <!-- End Row -->
				<div class="row welcome welcome_details">
					<div class="col-lg-6 col-md-12">
						<div class="welcome_item">
							<img src="{% static 'images/1.jpg' %}" alt="images">
							<div class="welcome_info">
								<h3>Investment Planning</h3>
								<p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non numquam eius modi.</p>
							</div>
						</div>
						<div class="welcome_item welcome_item_bottom">
							<img src="{% static 'images/2.jpg' %}" alt="images">
							<div class="welcome_info">
								<h3>Saving & Investments</h3>
								<p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non numquam eius modi.</p>
							</div>
						</div>
					</div>
					<div class="col-lg-6 col-md-12 bottom_row">
						<div class="welcome_item">
							<img src="{% static 'images/3.jpg' %}" alt="images">
							<div class="welcome_info">
								<h3>Mutual Funds</h3>
								<p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non numquam eius modi.</p>
							</div>
						</div>
						<div class="welcome_item welcome_item_bottom">
							<img src="{% static 'images/4.jpg' %}" alt="images">
							<div class="welcome_info">
								<h3>Retirements</h3>
								<p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non numquam eius modi.</p>
							</div>
						</div>
					</div>
				</div> <!-- End Row -->
			</div> <!-- End container -->
		</section> <!-- End welcome_sec -->
<!-- ======= /Welcome section ======= -->

<!-- ======= Who We Are ======= -->
		<section class="we_are">
			<div class="left_side float_left">
				<div class="we_are_opacity">
					<div class="we_are_border">
						<h2>We are E.s.t 2005</h2>
					</div>
				</div>
			</div> <!-- End Left_Side -->
			<div class="right_side float_right">
				<div class="we_are_deatails">
					<h2>Who We Are</h2>
					<p>Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. <br>  <br>

					Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
					<div class="list_item">
						<img src="{% static 'images/icon-1.png' %}" alt=""><p>Dedicated <br>Team</p>
						<img src="{% static 'images/icon-2.png' %}" alt=""><p>Best <br>Advisors</p>
						<img src="{% static 'images/icon-3.png' %}" alt=""><p class="support">24/7 <br>Supports</p>
					</div>
				</div>
			</div> <!-- End right_side -->
		</section> <!-- End We Are -->
<!-- ======= /Who We Are ======= -->

<!-- ======= Testimonial & Company Values ======= -->
		<section class="testimonial_sec clear_fix">
			<div class="container">
				<div class="row">
					<div  class="col-lg-5 col-md-12 col-sm-12 col-xs-12 testimonial_container">
						<div class="sec-title">
							<h2>Testimonials</h2>
						</div>
						<div id="owl">
							<div>
								<div class="testimonial">
									<img class="round_img" src="{% static 'images/7.jpg' %}" alt="images">
									<div class="float_right client_info">
										<p>MeFinance is Great Firm</p>
										<span>Michale John (CEO & Founder)</span>
										<ul>
											<li><a href=""></a></li>
											<li><a href=""></a></li>
											<li><a href=""></a></li>
											<li><a href=""></a></li>
											<li><a href=""></a></li>
										</ul>
									</div>
								</div>
								<p class="john_speach">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia numquam eius modi. Neque porro quisquam est, qui dolorem ipsum </p>
								<img src="{% static 'images/sign.jpg' %}" alt="images">
							</div>
.						</div> <!-- End owl -->
					</div>
					<div class="col-lg-7 col-md-12 col-sm-12 col-xs-12 company">
						<h2>Our Company Values</h2>
						<div class="company-tab">
							<ul class="nav nav-pills nav-justified">
							    <li class="active"><a data-toggle="pill" href="#menu1">Quality</a></li>
							    <li><a data-toggle="pill" href="#menu2">Commitment</a></li>
							    <li><a data-toggle="pill" href="#menu3">Success</a></li>
						  	</ul>

							 <div class="tab-content">
							    <div id="menu1" class="tab-pane fade in active">
							      <h3>Our Company Quality</h3>
							      <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit. Red quia numquam eius modi. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur</p>
							      <ul class="p0">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							      <ul class="list-two">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							    </div>
							    <div id="menu2" class="tab-pane fade">
							      <h3>Our Company Quality</h3>
							      <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit. Red quia numquam eius modi. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur</p>
							      <ul class="p0">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							      <ul class="list-two">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							    </div>
							    <div id="menu3" class="tab-pane fade">
							      <h3>Our Company Quality</h3>
							      <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit sed quia non qui dolorem ipsum quia dolor sit amet, consectetur, adipis civelit. Red quia numquam eius modi. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur</p>
							      <ul class="p0">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							      <ul class="list-two">
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Our Company Growth</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">1000 Employed</a></li>
							      	<li><i class="fa fa-arrow-circle-right"></i><a href="">Customer Relationship</a></li>
							      </ul>
							    </div>
							 </div>
						</div>
					</div>
				</div> <!-- End row -->
			</div> <!-- End Container -->
		</section> <!-- testimonial -->
<!-- ======= /Testimonial & Company Values ======= -->
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %}Post Detail{% endblock title %}
{% block content %}
{% load static %}
<!-- ================== Blog Container ========== -->
		<section class="blog-container two-side-background single-blog-page faqs_sec"> <!-- faqs_sec use for style right side content -->
			<div class="container">
				<div class="row">
					<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 white-left left-content ptb-80">
						<!-- .single-blog-post -->
						<div class="single-blog-post single-page-content anim-5-all">
							<!-- .img-holder -->
							<div class="img-holder">
								<img src="{% static 'images/blog/14.jpg' %}" alt="">
							</div><!-- /.img-holder -->
							<div class="post-meta">
								<div class="date-holder">
									{% if post.published_date %}
                                        <div class="date">
                                            {{ post.published_date }}
                                        </div>
                                    {% endif %}
								</div>
                                {% if user.is_authenticated %}
                                    <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                                {% endif %}
								<div class="title-holder">
									<h1>{{ post.title }}</h1>
									<ul>
										<li><a href="#">Posted By: John Smith</a></li>
										<li><a href="#">Comments: 2</a></li>
										<li><a href="#"> Categories: Taxes & Accounts</a></li>
									</ul>
								</div>
							</div>
							<div class="content">
								<p>{{ post.text }}</p>

							</div>
						</div><!-- /.single-blog-post -->
					</div>

                    {% include 'blog/side-bar.html' %}
				</div>
			</div>
		</section>
<!-- ================== /Blog Container ========== -->
{% endblock %}

blog/templates/blog/search-form.html
<h4>Search</h4>
<form method="GET" action="{% url 'blog:search_results' %}">
	<input type="text" value="{{ request.GET.q }}" name="q" placeholder="Enter Search Keywords">
	<button type="submit"><span class="icon icon-Search"></span></button>
</form>