blog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from .views import ContactView, SearchResultsView
# from .views import SearchResultsView


app_name = 'blog'
urlpatterns = [
   #url(r'^$', views.post_list, name='post_list'),  # for redirect from http://127.0.0.1:8000/blog
   url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
   url(r'^post/new/$', views.post_new, name='post_new'),
   url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
   path('index', views.index, name='home'),
   # path('login', TemplateView.as_view(template_name="blog/login_prev.html")),
   path('about', TemplateView.as_view(template_name="blog/about.html"), name='about'),
   path('contact', ContactView.as_view(), name='contact'),
   # path('contact', views.get_name, name='contact'),
   path('thanks/', TemplateView.as_view(template_name="blog/thanks.html"), name='thanks'),
   path('search/', SearchResultsView.as_view(), name='search_results'),
   path('', views.post_list, name='post_list'),  # for redirect from http://127.0.0.1:8000/blog

    # note: убирать .html из адресной строки /htaccess????
]

mysite/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from blog import views
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('registration/', include('registration.urls')),
    path('account/', include('account.urls')),
    path('', views.index),# to do: add common app for index, about, contacts
    path('404page', TemplateView.as_view(template_name="404.html"), name='404page'),
]

registration/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login

app_name = 'registration'
urlpatterns = [
   url(r'^login/$', LoginView.as_view(), name='login'),
   url(r'^logout/$', LogoutView.as_view(), name='logout'),
   url(r'^logout-then-login/$', logout_then_login, name='logout_then_login'),
]

shop/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from .views import SearchResultsView, CheckoutView

app_name = 'shop'
urlpatterns = [
    path('', views.shop_list, name='list'),  # for redirect from http://127.0.0.1:8000/shop
    path('search/', SearchResultsView.as_view(), name='search-results'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('thanks/', views.thanks, name='thanks'),
    path('order_complete/', views.order_complete, name='order-complete'),
    url(r'^cart-update/(?P<pk>\d+)/$', views.cart_update, name='cart-update'),
    url(r'^item-remove/(?P<pk>\d+)/$', views.item_remove, name='item-remove'),
    url(r'^add/(?P<pk>\d+)/$', views.add_to_cart, name='add-to-cart'),
    url(r'^details/(?P<pk>\d+)/$', views.product_details, name='product-details'),


]

templates/base.html
{% load static %}
<html>
    <head>
        <title>{% block title %}MyBlog{% endblock title %}</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">


		<!-- Bootstrap CSS -->
		<!--<link rel="stylesheet" type="text/css" href="css/bootstrap/bootstrap.css" media="screen">-->


		<!-- Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500italic,500,700,700italic' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Raleway:400,500,300,600,700,800,900' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic,800,300,300italic' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=PT+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

		<!-- Font Awesome -->
		<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}">
		<!-- Stroke Gap Icon -->
		<link rel="stylesheet" href="{% static 'fonts/stroke-gap/style.css' %}">

		<!-- Custom Css -->
		<link rel="stylesheet" href="{% static 'css/custom/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/responsive/responsive.css' %}">
        <style>
           .error{color:red;}
        </style>



    </head>
    <body>
		 <!--<div class="page-header">
			{% if user.is_authenticated %}
			     <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
		    {% endif %}
			<h1><a href="/">Django Girls Blog1</a></h1>
		 </div>-->

		 {% include "header.html" %}
         {% block content %}
		 {% endblock %}


	     {% include "footer.html" %}
    </body>
</html>

templates/footer.html
{% load static %}
<!-- ============ free consultation ================ -->
		<section class="container-fluid consultation">
			<div class="container">
				<p>If you have any querry for related investment  ... We are available</p>
				<a href="{% url 'blog:contact' %}">Contact us <i class="fa fa-arrow-circle-right"></i></a>
			</div>
		</section> <!-- End consultation -->
<!-- ============ /free consultation ================ -->
<!-- ============= Footer ================ -->
		<footer>
			<div class="top_footer container-fluid">
				<div class="container">
					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-12 part1">
							<a href=""><img src="{% static 'images/logo-footer.png' %}" alt="Logo"></a>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ali qua. </p>
							<p><i class="fa fa-phone"></i>&nbsp;&nbsp; 1800 - 254 - 9874</p>
							<p>contact@mefinance.com</p>
							<ul class="p0">
								<li><a href=""><i class="fa fa-facebook"></i></a></li>
								<li><a href=""><i class="fa fa-twitter"></i></a></li>
								<li><a href=""><i class="fa fa-google-plus"></i></a></li>
								<li><a href=""><i class="fa fa-linkedin"></i></a></li>
								<li><a href=""><i class="fa fa-skype"></i></a></li>
							</ul>
						</div>
						<div class="col-lg-2 col-md-3 col-sm-12 part2">
							<h5>Our Services</h5>
							<ul class="p0">
								<li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;Investment Planning</a></li>
								<li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;Retairment Planning</a></li>
								<li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;Mutial Funds</a></li>
								<li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;Saving & Investments</a></li>
								<li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;Tax Advisory Service</a></li>
							</ul>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-12 part3">
							<h5>Twitter Feeds</h5>
							<div class="twitter"></div>
						</div>
						<div class="col-lg-3 col-md-2 col-sm-12 part4">
							<h5>Flickr Widget</h5>
							<div class="gallery">
								<img src="{% static 'images/f-1.jpg' %}" alt="image">
								<img src="{% static 'images/f-2.jpg' %}" alt="image">
								<img src="{% static 'images/f-3.jpg' %}" alt="image">
								<img src="{% static 'images/f-4.jpg' %}" alt="image">
								<img src="{% static 'images/f-5.jpg' %}" alt="image">
								<img src="{% static 'images/f-6.jpg' %}" alt="image">
							</div>
						</div>
					</div> <!-- End row -->
				</div>
			</div> <!-- End top_footer -->
			<div class="bottom_footer container-fluid">
				<div class="container">
					<p class="float_left">Copyright &copy; MeFinance 2015. All rights reserved. </p>
					<p class="float_right">Created by: DesignArc</p>
				</div>
			</div> <!-- End bottom_footer -->
		</footer>
<!-- ============= /Footer =============== -->

		<!-- Js File -->

		<!-- j Query -->
		<script type="text/javascript" src="{% static 'js/jquery-2.1.4.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/validate.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.bxslider.min.js' %}"></script>
        <!-- <script src="{% static 'js/rango-jquery.js' %}"></script>-->
		<script src="{% static 'js/revolution-slider/jquery.themepunch.tools.min.js' %}"></script> <!-- Revolution Slider Tools -->
		<script src="{% static 'js/revolution-slider/jquery.themepunch.revolution.min.js' %}"></script> <!-- Revolution Slider -->
		<script type="text/javascript" src="{% static 'js/revolution-slider/extensions/revolution.extension.actions.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/revolution-slider/extensions/revolution.extension.carousel.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/revolution-slider/extensions/revolution.extension.kenburn.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/revolution-slider/extensions/revolution.extension.layeranimation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/revolution-slider/extensions/revolution.extension.migration.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/revolution-slider/extensions/revolution.extension.navigation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/revolution-slider/extensions/revolution.extension.parallax.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/revolution-slider/extensions/revolution.extension.slideanims.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/revolution-slider/extensions/revolution.extension.video.min.js' %}"></script>

		<!-- Bootstrap JS -->
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.appear.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
		<!-- Custom & Vendor js -->
		<script src="http://maps.google.com/maps/api/js"></script> <!-- Gmap Helper -->
		<script src="{% static 'js/gmap.js' %}"></script> <!-- gmap JS -->
		<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.mixitup.min.js' %}"></script>




templates/header.html
{% load static %}
<!-- =======Header ======= -->
		<header>
			<div class="container-fluid top_header">
				<div class="container">
					{% if request.user.is_authenticated %}
						<p class="float_left">Welcome to Me Financial Services, {{ request.user.first_name }}</p>
					{% else %}
						<p class="float_left">Welcome to Me Financial Services, guest</p>
					{% endif %}


					<div class="float_right">
						<ul>
							<li><a href=""><i class="fa fa-facebook"></i></a></li>
							<li><a href=""><i class="fa fa-twitter"></i></a></li>
							<li><a href=""><i class="fa fa-google-plus"></i></a></li>
							<li><a href=""><i class="fa fa-linkedin"></i></a></li>
							<li>
								<div  id="search_box">
									<input id="search" type="text" placeholder="Search here">
									<button id="button" type="submit"><span class="icon icon-Search"></span></button>
								</div>
							</li>
						</ul>
					</div>
				</div> <!-- end container -->
			</div><!-- end top_header -->
			<div class="bottom_header top-bar-gradient">
				<div class="container clear_fix">
					<div class="float_left logo">
						<a href="{% url 'blog:home' %}">
							<img src="{% static 'images/logo.png' %}" alt="Me Finance">
						</a>
					</div>
					<div class="float_right address">
						<div class="top-info">
							<div class="icon-box">
								<span class=" icon icon-Pointer"></span>
							</div>
							<div class="content-box">
								<p> 13005 Greenville Avenue <br><span>California, TX 70240</span></p>
							</div>
						</div>
						<div class="top-info">
							<div class="icon-box">
								<span class="separator icon icon-Phone2"></span>
							</div>
							<div class="content-box">
								<p>+ (1800) 456 7890 <br><span>info@mefinance.com</span></p>
							</div>
						</div>
						<div class="top-info">
							<div class="icon-box">
								<span class="separator icon icon-Timer"></span>
							</div>
							<div class="content-box">
								<p>Mon - Sat 9.00 - 19.00 <br><span>Sunday Closed</span></p>
							</div>
						</div>
					</div>
				</div> <!-- end container -->
			</div> <!-- end bottom_header -->
		</header> <!-- end header -->
<!-- ======= /Header ======= -->
<!-- ======= mainmenu-area section ======= -->
		<section class="mainmenu-area stricky">
			<div class="container">
				<nav class="clearfix">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header clearfix">
				      <button type="button" class="navbar-toggle collapsed">
				        <span class="sr-only">Toggle navigation</span>
				        <span class="fa fa-th fa-2x"></span>
				      </button>
				    </div>
					<div class="nav_main_list custom-scroll-bar pull-left" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav" id="hover_slip">
							<li><a href="{% url 'blog:home' %}">Home</a></li>
							<li class="arrow_down"><a href="{% url 'blog:about' %}">About Us</a></li>
							<li class="arrow_down"><a href="#">Pages</a>
								<div class="sub-menu">
									<ul>
										<li><a href="{% url '404page' %}">404 page</a></li>
									</ul>
								</div>
							</li>

							<li class="arrow_down" ><a href="{% url 'blog:post_list' %}">Blogs</a>
								<div class="sub-menu">
									{% if request.user.is_authenticated %}
										<ul>
											<li><a href="{% url 'blog:post_new' %}">New Post</a></li>
										</ul>
									{% endif %}
								</div>
							</li>
							<li class="arrow_down" ><a href="{% url 'shop:list' %}">Shop</a>
								<div class="sub-menu">
									<ul>
										<li><a href="{% url 'shop:product-details' pk=1 %}">Product Details</a></li>
										<li><a href="{% url 'shop:cart' %}">Cart Page</a></li>
										<li><a href="{% url 'shop:checkout' %}">Checkout Page</a></li>
									</ul>
								</div>
							</li>
							<li><a class="contact" href="{% url 'blog:contact' %}">Contact Us</a></li>
						</ul>
					</div>
					<div class="find-advisor pull-right">

						{% if request.user.is_authenticated %}
							<a href="{% url 'registration:logout' %}" class="advisor ">Logout</a>
						{% else %}
							<a href="{% url 'registration:login' %}" class="advisor ">Login</a>
						{% endif %}


					</div>
				</nav> <!-- End Nav -->
			</div> <!-- End Container -->
		</section>
<!-- ======= /mainmenu-area section ======= -->