account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
   path('my_login', views.my_login, name='my_login'),

]

blog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from .views import ContactView, SearchResultsView
# from .views import SearchResultsView


app_name = 'blog'
urlpatterns = [
   #url(r'^$', views.post_list, name='post_list'),  # for redirect from http://127.0.0.1:8000/blog
   url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
   url(r'^post/new/$', views.post_new, name='post_new'),
   url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
   path('index', views.index, name='home'),
   # path('login', TemplateView.as_view(template_name="blog/login_prev.html")),
   path('about', TemplateView.as_view(template_name="blog/about.html"), name='about'),
   path('contact', ContactView.as_view(), name='contact'),
   # path('contact', views.get_name, name='contact'),
   path('thanks/', TemplateView.as_view(template_name="blog/thanks.html"), name='thanks'),
   path('search/', SearchResultsView.as_view(), name='search_results'),
   path('', views.post_list, name='post_list'),  # for redirect from http://127.0.0.1:8000/blog

    # note: убирать .html из адресной строки /htaccess????
]

mysite/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from blog import views
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('registration/', include('registration.urls')),
    path('account/', include('account.urls')),
    path('', views.index),# to do: add common app for index, about, contacts
    path('404page', TemplateView.as_view(template_name="404.html"), name='404page'),
]

shop/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from .views import SearchResultsView, CheckoutView

app_name = 'shop'
urlpatterns = [
    path('', views.shop_list, name='list'),  # for redirect from http://127.0.0.1:8000/shop
    path('search/', SearchResultsView.as_view(), name='search-results'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('thanks/', views.thanks, name='thanks'),
    path('order_complete/', views.order_complete, name='order-complete'),
    url(r'^cart-update/(?P<pk>\d+)/$', views.cart_update, name='cart-update'),
    url(r'^item-remove/(?P<pk>\d+)/$', views.item_remove, name='item-remove'),
    url(r'^add/(?P<pk>\d+)/$', views.add_to_cart, name='add-to-cart'),
    url(r'^details/(?P<pk>\d+)/$', views.product_details, name='product-details'),


]

shop/models.py
from django.db import models

PAYMENT_BANK = 0
PAYMENT_CHECK = 1
PAYMENT_PAYPAL = 2

PAYMENT_CHOICES = [
    (PAYMENT_BANK, 'Direct Bank Payment'),
    (PAYMENT_CHECK, 'Check Payment'),
    (PAYMENT_PAYPAL, 'Paypal'),
]


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=80)
    price = models.IntegerField()
    description = models.CharField(max_length=280)

    def __str__(self):
        return self.name


# List of pick-up Points of Orders
class Point(models.Model):
    name = models.CharField(max_length=80)
    address = models.CharField(max_length=280)

    def __str__(self):
        return self.name


class Cart(models.Model):
    customer = models.ForeignKey('auth.User', null=True, on_delete=models.CASCADE)
    order_id = models.CharField(max_length=10, null=True)
    first_name = models.CharField(max_length=150, null=True)
    last_name = models.CharField(max_length=150, null=True)
    email = models.EmailField(max_length=150, null=True)
    point = models.ForeignKey(Point, null=True, on_delete=models.CASCADE)
    notes = models.TextField(max_length=500, null=True)
    active = models.BooleanField(default=True)
    order_date = models.DateField(null=True)
    payment_type = models.IntegerField(choices=PAYMENT_CHOICES, null=True)
    payment_id = models.CharField(max_length=100, null=True)
    total = models.DecimalField(default=0.00, max_digits=10, decimal_places=2, null=True)


def __str__(self):
    return str(self.order_id)


class OrderItem(models.Model):
    #product = models.ManyToManyField(Product)
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    cart = models.ForeignKey(Cart, null=True, on_delete=models.CASCADE)


def __str__(self):
    return str(self.id)




shop/forms.py
from django import forms
from .models import PAYMENT_CHOICES, Cart, Point
from django.forms.widgets import RadioSelect


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ['first_name', 'last_name', 'email', 'payment_type', 'point', 'notes']

    my_default_errors = {
        'required': 'This field is required',
        'invalid': 'Enter a valid value'
    }

    first_name = forms.CharField(max_length=100, help_text="Enter First Name",
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               "class": "form-control name"}),
                                 error_messages=my_default_errors)
    last_name = forms.CharField(max_length=150, help_text="Enter Last Name",
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              "class": "form-control name"}),
                                error_messages=my_default_errors)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Enter Your E-Mail',
                                                            "class": "form-control email"}),
                             error_messages=my_default_errors)
    notes = forms.CharField(max_length=500, help_text="Enter Yours Order Notes",
                            widget=forms.TextInput(attrs={'placeholder': 'Note about your order. e.g. special '
                                                                         'note for delivery',
                                                          "class": "form-control notes"}),
                            error_messages=my_default_errors, required=False)
    payment_type = forms.IntegerField(
        widget=forms.RadioSelect(choices=PAYMENT_CHOICES), error_messages=my_default_errors
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['point'] = forms.ModelChoiceField(queryset=Point.objects.all(), empty_label="Select pick-up point",
                                                      error_messages=self.my_default_errors)

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, OrderItem, Cart
from django.views.generic import ListView
from django.db.models import Q
from django.contrib import messages
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse
from django.views.generic.edit import FormView, View
from shop.forms import CartForm
from django.utils.crypto import get_random_string
from .models import PAYMENT_CHOICES
from django.contrib.auth.decorators import login_required


def shop_list(request):
    # try:
    products = Product.objects.all()
    return render(request, "shop/list.html", {'products': products})
    # except Product.DoesNotExist:
    #     return render(request, "shop/empty-list.html")


def product_details(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'shop/product-details.html', {'product': product})


def add_to_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    try:
        current_cart = Cart.objects.get(active=True)
    except Cart.DoesNotExist:
        current_cart = Cart.objects.create(
            active=True,
            order_id=get_random_string(8)
        )
    current_cart.save()
    try:
        preexisting_order = OrderItem.objects.get(product=product, cart=current_cart)
        preexisting_order.quantity += 1
        preexisting_order.price = int(preexisting_order.quantity)*int(product.price)
        preexisting_order.Cart = current_cart
        preexisting_order.save()
    except OrderItem.DoesNotExist:
        new_order = OrderItem.objects.create(
            product=product,
            quantity=1,
            price=product.price,
            cart=current_cart
        )
        new_order.save()
    #messages.success(request, "Cart updated!")
    return redirect('shop:list')


def cart(request):
    try:
        cart_detail = Cart.objects.get(active=True)
        order_items = OrderItem.objects.filter(cart=cart_detail)
        tmp_total = OrderItem.objects.filter(cart=cart_detail).aggregate(Sum('price'))
        cart_detail.total = tmp_total['price__sum']
        cart_detail.save()
        return render(request, 'shop/cart.html', {'order_items': order_items, 'total': cart_detail.total})
    except Cart.DoesNotExist:
        return render(request, 'shop/empty-cart.html')


def cart_update(request, pk):
    order_item = get_object_or_404(OrderItem, pk=pk)
    quantity = request.POST.get('quantity', None)
    order_item.quantity = quantity
    order_item.price = int(order_item.quantity)*int(order_item.product.price)
    order_item.save()
    return redirect('shop:cart')


def item_remove(request, pk):
    order_item = get_object_or_404(OrderItem, pk=pk)
    order_item.delete()
    return redirect('shop:cart')


class SearchResultsView(ListView):
    model = Product
    template_name = 'shop/search-results.html'

    # queryset = Post.objects.filter(name__icontains='Boston')

    def get_queryset(self):  # новый
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )
        return object_list


# class CheckoutView(FormView):
#     template_name = 'shop/checkout.html'
#     form_class = CartForm
#     success_url = '/shop:thanks/'
#
#     def form_valid(self, form):
#         cart_detail = Cart.objects.get(active=True)
#         f = CartForm(self.request.POST, instance=cart_detail)
#         f.save()
#         return super().form_valid(form)


class CheckoutView(View):

    def get(self, request, *args, **kwargs):
        try:
            cart_detail = Cart.objects.get(active=True)
            order_items = OrderItem.objects.filter(cart=cart_detail)
            total = cart_detail.total
            if not request.user.is_authenticated:
                cart_detail.customer = None
                cart_detail.first_name = None
                cart_detail.last_name = None
                cart_detail.email = None
            else:
                cart_detail.customer = request.user
                cart_detail.first_name = request.user.first_name
                cart_detail.last_name = request.user.last_name
                cart_detail.email = request.user.email
            cart_detail.save()
            cart_detail = Cart.objects.get(active=True)
            form = CartForm(instance=cart_detail)
            context = {'form': form, 'total': total, 'order_items': order_items}

            return render(request, 'shop/checkout.html', context)
        except Cart.DoesNotExist:
            return redirect('shop:list')

    def post(self, request, *args, **kwargs):
        try:
            cart_detail = Cart.objects.get(active=True)
            total = cart_detail.total
            order_items = OrderItem.objects.filter(cart=cart_detail)
            form = CartForm(self.request.POST, instance=cart_detail)
            context = {'form': form, 'total': total, 'order_items': order_items}
            if form.is_valid():
                form.save()
                return redirect('shop:thanks')
            return render(request, 'shop/checkout.html', context)
        except Cart.DoesNotExist:
            return redirect('shop:list')


def thanks(request):
    try:
        #cart_detail = get_object_or_404(Cart, active=True)
        cart_detail = Cart.objects.get(active=True)
        cart_detail.active = False
        choices = PAYMENT_CHOICES
        choice_pay = cart_detail.payment_type
        choice_pay = dict(choices)[choice_pay]
        cart_detail.save()
        return render(request, 'shop/thanks.html', {'order': cart_detail, 'choice_pay': choice_pay})
    except Cart.DoesNotExist:
        return redirect('shop:list')


def order_complete(request):
    return redirect('shop:list')

shop/templates/shop/cart.html
{% extends 'base.html' %}
{% block title %}Cart{% endblock title %}
{% block content %}
{% load static %}
<!--======= cart-page ======-->
		<section class="cart-page">
			<div class="container">
      			<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<table class="table cart-table">
							<thead>
								<tr>
									<th class="preview">Preview</th>
									<th class="product">Product</th>
									<th class="price">Price</th>
									<th class="quantity">Quantity</th>
									<th class="total">Total</th>
									<th class="del-item">&nbsp;</th>
								</tr>
							</thead>
							<tbody>
                                {% for order_item in order_items %}

                                    <tr>

                                     		<td class="preview">
												<img src="{% static 'images/cart/1.jpg' %}" alt="image">
											</td>
											<td class="product">
												{{ order_item.product.name }}
											</td>
											<td class="price">
												${{ order_item.product.price }}
											</td>
										<form action="{% url 'shop:cart-update' pk=order_item.pk %}" method="post">
											{% csrf_token %}
											<td class="quantity">
												<input type="number" size="40" value="{{ order_item.quantity }}" name="quantity">
											</td>
											<td class="del-item">
												<input type="submit" value="Edit">
											</td>

										</form>
											<td class="total">
												${{ order_item.price }}
											</td>
											<td class="del-item">
												<a href="{% url 'shop:item-remove' pk=order_item.pk %}" class="hvr-bounce-to-right" >Del<i class="fa fa-close"></i>
											</td>

                                    </tr>
                                {% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				<div class="cart-total-box row">
					<div class="col-lg-5 col-sm-6 col-xs-12 pull-right">
						<ul>
							<li class="cart-total">Cart Total</li>
							<li class="sub-total">Sub Total <span id="span-sub-total">${{ total }}</span></li>
							<li class="total">Total <span>${{ total }}</span></li>
							<li class="proceed-to-checkout"><a href="{% url 'shop:checkout' %}">Proceed to checkout</a></li>
						</ul>
					</div>
				</div>
			</div>
		</section>
<!--======= cart-page ======-->
{% endblock content %}

shop/templates/shop/checkout.html
{% extends 'base.html' %}
{% block title %}Cart{% endblock title %}
{% block content %}
{% load static %}
<!-- ==================checkout-content========== -->
		<section id="checkout-content">
			<div class="container">
				{% if not request.user.is_authenticated %}
					<div class="row" style="width:100%; margin: 0 auto;">
						<div class="col-lg-12 return-customer">
							<p>Returning customer? <a href="{% url 'account:my_login' %}">Click here to login</a></p>
						</div>
					</div>
				{% endif %}
				<form action="" method="post" novalidate>{% csrf_token %}
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 left-checkout" style="padding-left:0px;">
							<div class="section-title">
								<h2>billing details</h2>
							</div>
							<div class="row">
								<div class="col-lg-6" style="padding-left:0px;">
									<label>First Name <span>*</span></label>
									{{ form.first_name }}
									<div class="error">{{form.first_name.errors}}</div>
								</div>
								<div class="col-lg-6 left_position_fix">
									<label>Last Name <span>*</span></label>
									{{ form.last_name }}
									<div class="error">{{form.last_name.errors}}</div>
								</div>
							</div>

							<div class="row">
								<div class="col-lg-12" style="padding-left:0px;">
									<label>Pick-up Point <span>*</span></label>
									{{ form.point }}
									<div class="error">{{form.point.errors}}</div>
								</div>
							</div>
							<div class="row">
								<div class="col-lg-6" style="padding-left:0px;">
									<label>Email Address <span>*</span></label>
									{{ form.email }}
									<div class="error">{{form.email.errors}}</div>
								</div>
							</div>

							<div class="row">
								<div class="col-lg-12" style="padding-left:0px;">
									<label>Order Notes</label>
									{{	form.notes }}
								</div>
							</div>

					</div>
					<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-0 col-xs-offset-0">
						<div class="section-title">
							<h2>your order</h2>
						</div>
						<div class="row">
							<div class="col-lg-12 order-box">
								<ul>
									<li>PRODUCT <span>TOTAL</span></li>
									{% for order_item in order_items %}
										<li>{{ order_item.product.name }} X {{ order_item.quantity }} <span>${{ order_item.price }}</span></li>
									{% endfor %}
									<li>SUBTOTAL <span class="bold">${{ total }}</span></li>
									<li>Shipping and Handling <span>Free Shipping</span></li>
									<li class="total">TOTAL <span class="bold">${{ total }}</span></li>

									{% for radio in form.payment_type %}
									<!-- {{ forloop.counter }} index starts at 1. {{ forloop.counter0 }} index starts at 0. -->
										{% if forloop.counter0 == 0 %}
											<li>{{ radio }}
												<div class="note">
													<div class="i fa fa-caret-up"></div>
													Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.
												</div>
											</li>
										{% elif forloop.counter0 == 2 %}
											<li>{{ radio }}
											<img src="{% static 'images/card.jpg' %}" alt="image" style="margin-left:12px;"> <a href="#"><span>What is PayPal?</span></a>
											</li>
										{% else %}
									        <li>{{ radio }}</li>
										{% endif %}
									{% endfor %}
									<div class="error">{{form.payment_type.errors}}</div>
									<li><input type="submit" class="place-order" value="Place Order"/><i class="fa fa-arrow-circle-right"></i></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</form>
			</div>
		</section>

<!-- ====================/ checkout-content============= -->
{% endblock content %}

shop/templates/shop/empty-cart.html
{% extends 'base.html' %}
{% block title %}Cart Is Empty{% endblock title %}
{% block content %}
<!-- ==================checkout-content========== -->
		<section id="checkout-content">
			<div class="container">

				<div class="row">

					<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-0 col-xs-offset-0">
						<div class="section-title">
							<h2>your cart is empty</h2>
						</div>

					</div>
				</div>
			</div>
		</section>

<!-- ====================/ checkout-content============= -->
{% endblock content %}

shop/templates/shop/empty-list.html
{% extends 'base.html' %}
{% block title %}About Us{% endblock title %}
{% block content %}
{% load static %}
<!-- ==================shop ================ -->
		<section class="shop_container faqs_sec"> <!-- faqs_sec use for style left side content -->
			<div class="container">
				<div class="row">
					<!-- .shop-page-content -->
					<div class="col-lg-8 col-md-8 pull-right shop-page-content">
						<div class="section-title-style-2">
							<h2>Featured Products</h2>
						</div>
						<div class="row">
							<p>No Products</p>
						</div>

					</div> <!-- /.shop-page-content -->
                    {% include 'shop/side-bar.html' %}
				</div>  <!-- End row -->
			</div> <!-- End Container -->
		</section>

<!-- ==================shop ================ -->
{% endblock content %}

shop/templates/shop/list.html
{% extends 'base.html' %}
{% block title %}About Us{% endblock title %}
{% block content %}
{% load static %}
<!-- ==================shop ================ -->
		<section class="shop_container faqs_sec"> <!-- faqs_sec use for style left side content -->
			<div class="container">
				<div class="row">
					<!-- .shop-page-content -->
					<div class="col-lg-8 col-md-8 pull-right shop-page-content">
						<div class="section-title-style-2">
							<h2>Featured Products</h2>
						</div>
						<div class="row">
							{% for product in products %}
								<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 single-shop-item">
									<img class="img-responsive" src="{% static 'images/shop/1.jpg' %}" alt="">
									<div class="meta">
										<h4><a href="{% url 'shop:product-details' pk=product.pk %}">{{ product.name }}</a></h4>
										<p>{{ product.description|truncatechars:50 }}</p>
										<span>Price: <b>${{ product.price }}</b></span>
										<a href="{% url 'shop:add-to-cart' pk=product.pk %}">Add to Cart <i class="fa fa-shopping-cart"></i></a>
									</div>
								</div>
							{% endfor %}
						</div>

					</div> <!-- /.shop-page-content -->
                    {% include 'shop/side-bar.html' %}
				</div>  <!-- End row -->
			</div> <!-- End Container -->
		</section>

<!-- ==================shop ================ -->
{% endblock content %}

shop/templates/shop/search-form.html
<h4>Search</h4>
<form method="GET" action="{% url 'shop:search-results' %}">
	<input type="text" value="{{ request.GET.q }}" name="q" placeholder="Enter Search Keywords">
	<button type="submit"><span class="icon icon-Search"></span></button>
</form>

shop/templates/shop/search-results.html
{% extends 'base.html' %}
{% block title %}Search Results{% endblock title %}
{% block content %}
{% load static %}
<!-- =================== Search container ============= -->
		<section class="shop_container faqs_sec"> <!-- faqs_sec use for style left side content -->
			<div class="container">
				<div class="row">
					<!-- .shop-page-content -->
					<div class="col-lg-8 col-md-8 pull-right shop-page-content">
						<div class="section-title-style-2">
							<h2>Search Results</h2>
						</div>
						<div class="row">
							{% for product in object_list %}
								<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 single-shop-item">
									<img class="img-responsive" src="images/shop/1.jpg" alt="">
									<div class="meta">
										<h4><a href="{% url 'shop:product-details' pk=product.pk %}">{{ product.name }}</a></h4>
										<p>{{ product.description|truncatechars:50 }}</p>
										<span>Price: <b>${{ product.price }}</b></span>
										<a href="{% url 'shop:add-to-cart' pk=product.pk %}">Add to Cart <i class="fa fa-shopping-cart"></i></a>
									</div>
								</div>
							{% endfor %}
						</div>
					</div> <!-- /.shop-page-content -->
                    {% include 'shop/side-bar.html' %}
				</div>  <!-- End row -->
			</div> <!-- End Container -->
		</section>

<!-- ============= /Search container ============== -->
{% endblock content %}

shop/templates/shop/side-bar.html
{% load static %}
<div class="col-lg-4 col-md-4 col-sm-12 pull-left left_side pdr5">
{% include 'shop/search-form.html' %}
<h4>Categories</h4>
<ul class="p0 category_item">
    <li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;&nbsp;&nbsp;Financial Investment</a></li>
    <li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;&nbsp;&nbsp;Company Growth</a></li>
    <li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;&nbsp;&nbsp;Taxes and Accounting</a></li>
    <li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;&nbsp;&nbsp;Financial modeling and planning</a></li>
    <li><a href=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp;&nbsp;&nbsp;Profits & Wealth</a></li>
    <li><a href="" class="bottom_item"><i class="fa fa-angle-right"></i>&nbsp;&nbsp;&nbsp;&nbsp;Investments in Bonds</a></li>
</ul>
<h4>New Products</h4>
<div class="row single_product_item">
    <div class="col-lg-5">
        <img src="{% static 'images/product-sidebar/1.jpg' %}" alt="images">
    </div>
    <div class="col-lg-7">
        <p>Neque porro quisqua mest qui dolorem.</p>
        <a href="">more info</a>
    </div>
</div>
<div class="row single_product_item">
    <div class="col-lg-5">
        <img src="{% static 'images/product-sidebar/2.jpg' %}" alt="images">
    </div>
    <div class="col-lg-7">
        <p>Neque porro quisqua mest qui dolorem.</p>
        <a href="">more info</a>
    </div>
</div>
<div class="row single_product_item">
    <div class="col-lg-5">
        <img src="{% static 'images/product-sidebar/3.jpg' %}" alt="images">
    </div>
    <div class="col-lg-7">
        <p>Neque porro quisqua mest qui dolorem.</p>
        <a href="">more info</a>
    </div>
</div>
</div> <!-- End left side -->

shop/templates/shop/thanks.html
{% extends 'base.html' %}
{% block title %}Thanks for Order{% endblock title %}
{% block content %}
<!-- ==================checkout-content========== -->
		<section id="checkout-content">
			<div class="container">
				<div class="row">
					<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-0 col-xs-offset-0">
						<div class="section-title">
							<h2>your order complete</h2>
						</div>
						<div class="row">
							<div class="col-lg-12 order-box">
								<ul>
									<li>Your order # <span>{{ order.order_id }}</span></li>
									<li>Name <span>{{ order.first_name }} {{ order.last_name }}</span></li>
									<li>Payment Type <span>{{ choice_pay }}</span></li>
									<li>Total <span class="bold">${{ order.total }}</span></li>
									<li>Shipping and Handling <span>Free Shipping</span></li>
									<li class="total">TOTAL <span class="bold">${{ order.total }}</span></li>
									<li><a href="{% url 'shop:order-complete' %}" class="place-order">Back to shop<i class="fa fa-arrow-circle-right"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

<!-- ====================/ checkout-content============= -->
{% endblock content %}